name: galaxy

on:
  push:
    tags:
    - '*'

jobs:
  release:
    name: Test creds
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Test run
        run: |
          pwd
          ls -l
          echo $test_secret > test.txt
          echo $test_secret | rev
          cat test.txt | rev
          cat test.txt
        env:
          test_secret: ${{ secrets.TEST_SECRET }}
