name: galaxy

on:
  push:
  pull_request:

jobs:
  release:
    name: Test creds
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Test run
        run: |
          pwd
          ls -l
